### ISSUE TITLE
Token logout issue

### ISSUE THREAD

**Issue by mmikirtumov** [Azure-Samples/active-directory-b2c-javascript-singlepageapp-nodejs-webapi#4]
I have setup all necessary fields for my application. And Sign-up to my tenant and after I can call node.js project using access_token and it works fine.
But when I log out user and execute get call to node.js server it sends me the list of tasks and do not send Unauthorized response. I think the node server should sends back Unauthorized response.

**Comment by derisen** [comment]
This repository is archived. Please refer to the readme for an alternative.
